#!/bin/bash

if [ "$COLORTERM" = "roxterm" ]; then
    if [[ "$@" =~ (gearshift|crushinator|destructor|rusty|femputer|fatbot|clamps) ]]; then
        dbus-send --session /net/sf/roxterm/Options net.sf.roxterm.Options.SetColourScheme string:$ROXTERM_ID "string:red"
    fi

    if [[ "$@" =~ (boxy|frankie) ]]; then
        dbus-send --session /net/sf/roxterm/Options net.sf.roxterm.Options.SetColourScheme string:$ROXTERM_ID "string:blue"
    fi
fi

ssh $@

if [ "$COLORTERM" = "roxterm" ]; then
    dbus-send --session /net/sf/roxterm/Options net.sf.roxterm.Options.SetColourScheme string:$ROXTERM_ID "string:solarized-dark"
fi
